next-version: 4.2
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
mode: ContinuousDelivery
increment: Inherit
continuous-delivery-fallback-tag: ci
tag-prefix: '[vV]'
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
legacy-semver-padding: 4
build-metadata-padding: 4
commits-since-version-source-padding: 4
commit-message-incrementing: Enabled
commit-date-format: 'yyyy-MM-dd'
# ignore:
#   sha: []
#   commits-before: yyyy-MM-ddTHH:mm:ss
merge-message-formats: {}
branches:
  release_v:
    regex: ^release[_]v
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    source-branches: ['release']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
  release:
    regex: ^release$
    mode: ContinuousDelivery
    source-branches: []
    tag: beta
    increment: None
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    pre-release-weight: 1000
  develop:
    regex: ^develop$
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    source-branches: []
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false
  adf_release_v:
    regex: ^adf_release[_]v
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    source-branches: ['adf_release']
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
  adf_release:
    regex: ^adf_release$
    mode: ContinuousDelivery
    tag: beta
    increment: Patch
    source-branches: []
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: true
    pre-release-weight: 1000
  adf_develop:
    regex: ^adf_develop$
    mode: ContinuousDeployment
    tag: alpha
    increment: Minor
    source-branches: []
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false
